# Generated by Django 2.2.4 on 2019-08-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quizzes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_index', models.IntegerField()),
                ('quiz_string', models.CharField(max_length=3000)),
            ],
        ),
    ]
