# Generated by Django 2.2.4 on 2019-08-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createQuiz', '0002_quizzes_quiz_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='times_attempted',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
