# Generated by Django 2.2.4 on 2019-08-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createQuiz', '0003_quizzes_times_attempted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='times_attempted',
            field=models.IntegerField(default=0),
        ),
    ]
